app:
  port: 8080

upload:
  path: "./statics/uploads/"
  thumbnails_path: "./statics/thumbnails/"
  max_size: 10485760  # 10MB in bytes

private_files:
  path: "./uploads/private/"
  max_size: 104857600  # 100MB in bytes
  allowed_types: ".jpg,.jpeg,.png,.gif,.pdf,.doc,.docx,.xls,.xlsx,.txt"

database:
  host: "localhost"
  port: 5432
  username: "your_username"
  password: "your_password"


url:
  #imgurl: "https://imghost.3049589.xyz/uploads/"
  imgurl: "https://pic.3049589.xyz/uploads/"

permissions:
  routes:
    # 公开路由 - 不需要权限
    "/register": []
    "/login": []
    "/api/verify-token": []
    "/": []
    "/statics/*filepath": []
    
    # 图片相关路由
    "/images": ["view_all_images"]  # 查看所有图片需要特殊权限
    "/images/upload": ["upload_img"]
    "/images/batch-upload": ["upload_img"]
    "/images/search": ["search_img"]
  
    
    # 需要权限的路由
    "/imgupload": ["upload_img"]
    "/searchbytag": ["search_img"]
    "/createtag": ["createtag"]
    "/getalltag": ["search_img"]
    "/searchimg": ["search_img"]
    "/searchAllimg": ["search_img"]
    "/private-files": ["manage_private_files"]
    "/private-files/:id": ["manage_private_files"]
    "/private-files/search": ["manage_private_files"]
    "/private-files/:id/download": ["manage_private_files"]
    "/users": ["view_users"]
    "/users/:id": ["manage_users"]
    "/users/:id/status": ["manage_user_status"]
    "/users/:id/roles": ["manage_user_roles"]
    "/users/profile": []
    
    # 权限管理路由
    "/permissions/all": ["manage_permissions"]
    "/permissions/roles": ["manage_permissions"]
    "/permissions/roles/:role": ["manage_permissions"]
    "/permissions/create": ["manage_permissions"]
    "/permissions/roles/create": ["manage_permissions"]
    "/permissions/sync": ["manage_permissions"]
    "/permissions/users/:id/permissions": ["manage_permissions"]
    "/permissions/users/current/permissions": []  # 当前用户可以查看自己的权限，不需要特殊权限

    # 明确指定不同 HTTP 方法的权限
    "GET /images/:id": ["view_images"]     # GET 方法需要 view_images 权限
    "DELETE /images/:id": ["delete_images"] # DELETE 方法需要 delete_images 权限

  # 初始化角色和权限
  roles:
    admin:
      - "upload_img"
      - "search_img"
      - "view_all_images"  # 添加查看所有图片的权限
      - "view_images"
      - "delete_images"
      - "createtag"
      - "manage_private_files"
      - "view_users"
      - "manage_users"
      - "manage_user_status"
      - "manage_user_roles"
      - "manage_permissions"
    user:
      - "upload_img"
      - "search_img"
      - "view_images"
      - "delete_images"  # 用户可以删除自己的图片
      - "view_users"
      - "manage_user_roles"

log:
  path: "./logs/"           # 日志目录
  filename: "app.log"       # 日志文件名
  level: "info"            # 日志级别
  max_size: 100           # 单个日志文件最大尺寸(MB)
  max_age: 30            # 日志保留天数
  max_backups: 10       # 最大备份数
  compress: true        # 是否压缩
