app:
  port: 8080

database:
  host: "localhost"
  port: 5432
  username: "your_username"
  password: "your_password"


url:
  #imgurl: "https://imghost.3049589.xyz/uploads/"
  imgurl: "https://pic.3049589.xyz/uploads/"

permissions:
  routes:
    # 公开路由 - 不需要权限
    "/register": []
    "/login": []
    "/api/verify-token": []
    "/": []
    "/statics/*filepath": []
    
    # 需要权限的路由
    "/imgupload": ["upload_img"]
    "/searchbytag": ["search_img"]
    "/createtag": ["createtag"]
    "/getalltag": ["search_img"]
    "/searchimg": ["search_img"]
    "/searchAllimg": ["search_img"]
    "/private-files": ["manage_private_files"]
    "/private-files/:id": ["manage_private_files"]
    "/private-files/search": ["manage_private_files"]
    "/private-files/:id/download": ["manage_private_files"]
    "/users": ["view_users"]
    "/users/:id": ["manage_users"]
    "/users/:id/status": ["manage_user_status"]
    "/users/:id/roles": ["manage_user_roles"]
    "/users/profile": []
    
    # 权限管理路由
    "/permissions/all": ["manage_permissions"]
    "/permissions/roles": ["manage_permissions"]
    "/permissions/roles/:role": ["manage_permissions"]
    "/permissions/create": ["manage_permissions"]
    "/permissions/roles/create": ["manage_permissions"]
    "/permissions/sync": ["manage_permissions"]
    "/permissions/users/:id/permissions": ["manage_permissions"]
    "/permissions/users/current/permissions": []  # 当前用户可以查看自己的权限，不需要特殊权限

  # 初始化角色和权限
  roles:
    admin:
      - "upload_img"
      - "search_img"
      - "createtag"
      - "manage_private_files"
      - "view_users"
      - "manage_users"
      - "manage_user_status"
      - "manage_user_roles"
      - "manage_permissions"
    user:
      - "upload_img"
      - "search_img"
      - "view_users"
      - "manage_user_roles"
